Updated Travis CI script as per https://stackoverflow.com/questions/42731625/travis-ci-failed-because-cannot-accept-license-constrain-layout/42736695#42736695

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,74 +1,115 @@
-# Docs and examples to use:
-# https://docs.travis-ci.com/user/languages/android
-# http://panavtec.me/continous-integration-on-android-with-travis-ci
-# https://github.com/codecov/example-android/blob/master/.travis.yml
-# https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI
-# http://stackoverflow.com/questions/34621124/using-travis-ci-with-android
+# This script is based on this example:
+# https://stackoverflow.com/questions/42731625/travis-ci-failed-because-cannot-accept-license-constrain-layout/42736695#42736695
+# See also:
 # https://github.com/travis-ci/travis-ci/issues/6122 Android - Missing emulator ABI due to bad SDK Tools version
 language: android
 jdk: oraclejdk8
-
-sudo: required
+sudo: required # false for Container-Based Infrastructure, required for Sudo-enabled Infrastructure
 
 env:
   global:
-    - COMPILE_API_LEVEL=25
-    - ANDROID_BUILD_TOOLS_VERSION=25.0.3
-    # Using Emulator for an older Android version, because there is no newer emulator, which works in travis-ci
-    - EMULATOR_API_LEVEL=24
-    - EMULATOR_ABI=armeabi-v7a
-    - EMULATOR_TAG=google_apis
+#    - COMPILE_API_LEVEL=25
+    - ANDROID_BUILD_TOOLS_VERSION=25.0.3 # Match build-tools version used in build.gradle
+    - PROJECT_DIR=${TRAVIS_BUILD_DIR} # Project directory
+    - EMULATOR_API_LEVEL=25 # Android API level 25 by default
+    - EMULATOR_TAG=google_apis # Google APIs by default, alternatively use default
+    - EMULATOR_ABI=armeabi-v7a # ARM ABI v7a by default
+    - QEMU_AUDIO_DRV=none # Disable emulator audio to avoid warning
+    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle" # Change location for Gradle Wrapper and cache
+    - ANDROID_HOME=/usr/local/android-sdk-25.0.2 # Depends on the cookbook's version used in the VM
+    - TOOLS=${ANDROID_HOME}/tools # PATH order matters, exists more than one emulator script
+    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
     - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
 
+before_cache:
+  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock # Avoid to repack it due locks
+  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/classAnalysis/classAnalysis.lock
+  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/jarSnapshots/jarSnapshots.lock
+
+cache:
+  directories:
+    - ${TRAVIS_BUILD_DIR}/gradle/caches/
+    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
+
+notifications:
+  email: false
+
 android:
-  components:
-    - tools
-    - platform-tools
-    - tools
-    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
-    - android-$COMPILE_API_LEVEL
-    - android-$EMULATOR_API_LEVEL
-    - extra-google-m2repository
-    - extra-android-m2repository
-    # Specify at least one system image
-    - sys-img-$EMULATOR_ABI-google_apis-$EMULATOR_API_LEVEL
+  components: # Cookbooks version: https://github.com/travis-ci/travis-cookbooks/tree/9c6cd11
+    - tools # Update preinstalled tools from revision 24.0.2 to 24.4.1
+    - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
+    - platform-tools # Update platform-tools to revision 25.0.3+
+    - tools # Update tools from revision 24.4.1 to 25.2.5
+
+#matrix:
+#  include: # More Emulator API levels to build in parallel
+#    - env: EMULATOR_API_LEVEL=24
+#    - env: EMULATOR_API_LEVEL=23
+#    - env: EMULATOR_API_LEVEL=22
+#  allow_failures:
+#    - env: EMULATOR_API_LEVEL=23
+#    - env: EMULATOR_API_LEVEL=22
+#  fast_finish: false
 
 before_install:
-  # http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
-  - chmod +x gradlew
+  - export EMULATOR="system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_TAG};${EMULATOR_ABI}" # Used to install/create emulator
+  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning
+
+install:
+  # List and delete unnecessary components to free space
+  - sdkmanager --list || true
+  - sdkmanager --uninstall "system-images;android-15;default;armeabi-v7a"
+  - sdkmanager --uninstall "system-images;android-16;default;armeabi-v7a"
+  - sdkmanager --uninstall "system-images;android-17;default;armeabi-v7a"
+  - sdkmanager --uninstall "system-images;android-18;default;armeabi-v7a"
+  - sdkmanager --uninstall "system-images;android-19;default;armeabi-v7a"
+  - sdkmanager --uninstall "system-images;android-21;default;armeabi-v7a"
+  - sdkmanager --uninstall "extras;google;google_play_services"
+  - sdkmanager --uninstall "extras;android;support"
+  - sdkmanager --uninstall "platforms;android-10"
+  - sdkmanager --uninstall "platforms;android-15"
+  - sdkmanager --uninstall "platforms;android-16"
+  - sdkmanager --uninstall "platforms;android-17"
+  - sdkmanager --uninstall "platforms;android-18"
+  - sdkmanager --uninstall "platforms;android-19"
+  - sdkmanager --uninstall "platforms;android-20"
+  - sdkmanager --uninstall "platforms;android-21"
+  - sdkmanager --uninstall "build-tools;21.1.2"
+  # Update sdk tools to latest version and install/update components
+  - echo yes | sdkmanager "tools"
+  - echo yes | sdkmanager "platforms;android-25" # Latest platform required by SDK tools
+  - echo yes | sdkmanager "platforms;android-${EMULATOR_API_LEVEL}" # Android platform required by emulator
+  - echo yes | sdkmanager "extras;android;m2repository"
+  - echo yes | sdkmanager "extras;google;m2repository"
+  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
+  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
+  - echo yes | sdkmanager "${EMULATOR}" # Install emulator system image
+  # Create and start emulator
+  - echo no | avdmanager create avd -n acib -k "${EMULATOR}" -f --abi "${EMULATOR_ABI}" --tag "${EMULATOR_TAG}"
+  - ls -la $HOME/.android/**/*
+  - ls -la $HOME/**/*
+  - emulator -avd acib -engine classic -no-window -camera-back none -camera-front none -verbose -qemu -m 512 &
+  # Start adbd, wait for device connected and show android serial
+  - adb wait-for-device get-serialno
+  # Show version and download Gradle Wrapper if it's not already cached
+  - cd ${PROJECT_DIR} && ./gradlew --version
+  # Clean project and download missing dependencies and components
+  - cd ${PROJECT_DIR} && ./gradlew clean build
+  # Check components status
+  - sdkmanager --list || true
 
 before_script:
-  - uname -a
-  - android list targets
-  - ls -la $HOME/.android/**/*
-  - ls -la $HOME/**/*
-  # Create and start emulator
-  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $EMULATOR_ABI --tag $EMULATOR_TAG
-  - ls -la $HOME/.android/**/*
-  - ls -la $HOME/**/*
-  - cat $HOME/.android/avd/test.avd/config.ini
-  - cp res-src/avd_config.ini $HOME/.android/avd/test.avd/config.ini
-  - cat $HOME/.android/avd/test.avd/config.ini
-  - emulator -avd test -no-window &
-  - travis_wait 30 android-wait-for-emulator
-  # Previous command seems to end too early, so wait a bit more
-  # On multilined commands: https://gitlab.com/gitlab-org/gitlab-ci/issues/258 and http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines
-  - |
-    while ! adb shell getprop init.svc.bootanim; do
-      echo Waiting for boot animation to end
-      sleep 10
-    done
-  # Another method. Should print SDK version number to console
-  # See http://stackoverflow.com/questions/28195080/unknown-api-level-error-when-trying-to-run-instrumentation-test
-  - |
-    while ! adb shell getprop ro.build.version.sdk; do
-      echo Waiting for ro.build.version.sdk value from device
-      sleep 10
-    done
-  - adb devices
+  # Wait for emulator fully-booted and disable animations
+  - android-wait-for-emulator
+  - adb shell settings put global window_animation_scale 0 &
+  - adb shell settings put global transition_animation_scale 0 &
+  - adb shell settings put global animator_duration_scale 0 &
+  - sleep 30
   - adb shell input keyevent 82 &
+  - adb devices
 
 script:
+  - cd ${PROJECT_DIR}
   - |
     ./gradlew build assembleAndroidTest
     retval=$?
@@ -82,7 +123,7 @@ script:
   # - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
   # run:
   - |
-    ./gradlew :app:installDebugAndroidTest :app:installDebug
+    ./gradlew :app:installDebug :app:installDebugAndroidTest
     retval=$?
     if [ $retval -ne 0 ]; then
       echo "error on install, exit code: "$retval
@@ -113,18 +154,13 @@ script:
       echo "Test failure found"
       exit 1
     else
-      cat build/adb-test.log | grep "Test results for"
+      cat build/adb-test.log | grep "OK ("
     fi
 
-# See https://docs.travis-ci.com/user/languages/java/#Projects-Using-Gradle
-before_cache:
-  - ls -la $HOME/.gradle/**/*
-  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
-  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
-cache:
-  directories:
-    - $HOME/.gradle/caches/
-    - $HOME/.gradle/wrapper/
+after_script:
+  # Show tests and lint results
+  - cat ${PROJECT_DIR}/*/build/outputs/androidTest-results/connected/*
+  - cat ${PROJECT_DIR}/*/build/reports/lint-results.xml
 
 after_success:
   - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true
